name=CasaHadas_ProyectoImayina
version=2.0.0
author=Ing. Mecatrónico Milton Elias Pech Uc
maintainer=Milton <milton.ortmed@gmail.com>
sentence=Control de iluminacion, mecanismo de purpurina y audio para las Casas de Hadas del proyecto Imayina.
paragraph=Firmware para ESP32-S3 Super Mini con tira LED WS2812B, servo MG90S, blower de 5 V y reproductor DFPlayer Mini.
category=Device Control
url=https://github.com/milton-ortmed/CasaHadas_ProyectoImayina
architectures=esp32
depends=FastLED, ESP32Servo, DFRobotDFPlayerMini, Botones
